"""Device library for Sinergia VMC units (CPRO3OEM-K electronics) over Modbus RTU."""

from .device import (
    TIME_BAND_DAYS,
    TIME_BANDS_PER_DAY,
    Alarms,
    Calibrations,
    Command,
    CompressorStatusCode,
    DamperStatusCode,
    DigitalIO,
    Enables,
    FanSpeeds,
    FanStatusCode,
    Maintenance,
    ModeStatusCode,
    Outputs,
    Probes,
    RecircDamperStatusCode,
    Setpoints,
    Status,
    TimeBandCode,
    TimeBandSetpoints,
    TimeBands,
    UnitStatusCode,
    VmcDevice,
    time_band,
)

__all__ = [
    "TIME_BANDS_PER_DAY",
    "TIME_BAND_DAYS",
    "Alarms",
    "Calibrations",
    "Command",
    "CompressorStatusCode",
    "DamperStatusCode",
    "DigitalIO",
    "Enables",
    "FanSpeeds",
    "FanStatusCode",
    "Maintenance",
    "ModeStatusCode",
    "Outputs",
    "Probes",
    "RecircDamperStatusCode",
    "Setpoints",
    "Status",
    "TimeBandCode",
    "TimeBandSetpoints",
    "TimeBands",
    "UnitStatusCode",
    "VmcDevice",
    "time_band",
]

__version__ = "0.2.0"
